= Rust Rocks

An Asteroids-like game built for fun using link:https://github.com/Rust-SDL2/rust-sdl2[rust-SDL2] and link:https://github.com/amethyst/legion[Legion].

== Controls

Only xbox-pattern gamepad controls are currently supported. I use a Logitech F710 for testing.

Use the d-pad to navigate menu options, the left thumbstick to accelerate, the right thumbstick to aim, and the right bumper to shoot.

== Build

You may need to install development packages for SDL2 since not all of the features are bundled. These may include (on Fedora) `SDL2-devel`, `SDL2_gfx-devel`, and `SDL2_image-devel`.

Otherwise, simply invoke `cargo build` to compile.

== Run

Call `cargo run` from the root.

== Acknowledgements

The player ship sprite used by earlier versions of Rust Rocks is the "speedship" sprite created by MillionthVector (https://millionthvector.blogspot.com/p/free-sprites.html[source]) and distributed under https://creativecommons.org/licenses/by/4.0/[creative-commons 4.0]. The current version of Rust Rocks uses a sprite derived from speedship.

Rust Rocks uses the "Press Start 2P" font by Cody "CodeMan38" Boisclair (cody@zone38.net), distributed under the SIL Open Font License, Version 1.1. A copy of the license may be found next to the font file at resources/press-start-2p/LICENSE.txt.
