= Rust Rocks

An Asteroids-like game built for fun using link:https://github.com/Rust-SDL2/rust-sdl2[rust-SDL2] and link:https://github.com/amethyst/legion[Legion].

== Controls

Only xbox-pattern gamepad controls are currently supported. I use a Logitech F710 for testing.

Use the d-pad to navigate menu options, the left thumbstick to accelerate, the right thumbstick to aim, and the right bumper to shoot.

== Build

You may need to install development packages for SDL2 since not all of the features are bundled. These may include (on Fedora) `SDL2-devel`, `SDL2_gfx-devel`, and `SDL2_image-devel`.

Otherwise, simply invoke `cargo build` to compile.

== Run

Call `cargo run` from the root. Set `RUST_LOG=debug` to print the framerate every second, among other things.

== Design

The `main.rs` file contains the main loop, which instructs an active `Scene` to update every frame. A `Scene` is a distinct mode of interaction with the player. For example, the `TitleScene` presents the player with a menu to either start the game or quit. If they press start, the `TitleScene` is unloaded and replaced with a `GameScene`, which simulates the player and asteroids in the game proper. `Scene`s may generate events that the main loop responds to by unloading one scene and loading another. In this sense, `Scene`s form a finite state machine.

The `TitleScene` and `ScoreScene` are both very rudimentary at this point. The `GameScene` is more thought-out, and uses the Legion Entity Component System (ECS) to simulate asteroids, bullets, the player, and so on. This is a data-driven framework that allows us to compose "entities" together out of pieces of state, called "components." "Systems" impart behavior to entities with at least some subset of components, allowing us to share behavrio between entities with minimal coupling.

Because SDL2 objects are frequently not thread-safe (many of them do not implement Send), they may only be used by the main thread. This is why the systems for player input and for rendering are registered with Legion via `add_thread_local`: we cannot run them on a different thread. The remaining systems, however, are run off-main. The extent to which these actually parallelize is based on the read/write dependnecies of each system.

== Acknowledgements

The player ship sprite used by earlier versions of Rust Rocks is the "speedship" sprite created by MillionthVector (https://millionthvector.blogspot.com/p/free-sprites.html[source]) and distributed under https://creativecommons.org/licenses/by/4.0/[creative-commons 4.0]. The current version of Rust Rocks uses a sprite derived from speedship.

Rust Rocks uses the "Press Start 2P" font by Cody "CodeMan38" Boisclair (cody@zone38.net), distributed under the SIL Open Font License, Version 1.1. A copy of the license may be found next to the font file at resources/press-start-2p/LICENSE.txt.
